version: '3'

services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  web:
    build:
      dockerfile: Dockerfile.dev
      context: ./web
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  front:
    build:
      dockerfile: Dockerfile.dev
      context: ./front
    volumes:
      - /app/node_modules
      - ./front:/app
  admin:
    build:
      dockerfile: Dockerfile.dev
      context: ./admin
    volumes:
      - /app/node_modules
      - ./admin:/app
